name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - pip:
    - fastapi[all]
    - diffusers
    - transformers
    - torch
    - torchvision
    - accelerate
    - scipy
    - ftfy
    - mypy
    - ruff
    - black
    - ipykernel
    - ipywidgets